### PR TITLE
Print warning instead of erroring out when app host is not in topo

### LINKED ISSUE #49: Allow host apps to reference hosts not in topology
If an app adds a new host to the topology, allow that new host to be referenced in the scenario config for said app. Currently, if the host is not in the topology config then an error is thrown by `VerfiyScenario`.

stage: 'Creation'

### PR DESCRIPTION
**Pull request by activeshadow**
closes #49

### CODE REVIEW

**Comment by activeshadow** [comment]
@mgaliar please test this PR if you don't mind, as I have not tested it yet!

**Comment by activeshadow** [comment]
@mgaliar it should soon be available as `activeshadow/phenix:issue_49` from Docker Hub (once it's done building).

**Comment by mgaliar** [comment]
@activeshadow Sure, I'll test if out once it's done building.

**Comment by mgaliar** [comment]
@activeshadow Looks good to me. Gets what I need working :)

**Pull request merged**
