### PR TITLE
Initial commit to get rid of experiment vs. host app distinction

### LINKED ISSUE #34: Get rid of experiment vs host app distinction
Support scenario configs having both app-level metadata and host-level metadata for an app, and let the app code itself determine if it should be an experiment or host app (or both).

This will be a **breaking** change for any existing scenerios...

### PR DESCRIPTION
**Pull request by activeshadow**
closes #34

### CODE REVIEW

**Comment by activeshadow** [comment]
Needs testing with a scenario file that gets rid of the experiment/host distinction.

**Comment by activeshadow** [comment]
I've tested this locally and it works. However, as mentioned in the issue, it is a **breaking change** for existing deployments. Any deployments with experiments in the store that have a scenario will need to be updated to remove the experiment/host distinction between apps (as well as any scenarios in the store). This is simple to do, but must be done manually for each scenario and experiment in the store.

**Comment by activeshadow** [comment]
I don't want to merge this until we have a PR ready in the activeshadow/python-apps repo as well. @glattercj care to take a stab at that?

**Comment by glattercj** [comment]
Will also need a corresponding PR in base [phenix-apps](https://github.com/activeshadow/phenix-apps)

**Comment by glattercj** [comment]
> I don't want to merge this until we have a PR ready in the activeshadow/python-apps repo as well. @glattercj care to take a stab at that?

https://github.com/activeshadow/phenix-apps/pull/6

**Comment by glattercj** [comment]
LGTM

**Pull request merged**
