### PR TITLE
Support user apps not returning anything over STDOUT

### LINKED ISSUE #46: Allow user apps to not return anything over STDOUT if no modifications were made
This might be useful for simple, one-off, post-start apps (like a bash script) that just want to run some stuff after an experiment has started.

### PR DESCRIPTION
**Pull request by activeshadow**
closes #46

### CODE REVIEW

**Comment by glattercj** [comment]
I ran this in both `:issue_46` build and `:latest`. I used an app that just had a log() statement in the `post_start` method. Both were successful...not sure why `:latest` didn't fail without this PR?

**Comment by activeshadow** [comment]
@glattercj yeah, for the `post_start` stage I would expect that to be OK. I would expect it to mess things up in the `configure` or `pre_start` stages using the latest Docker image though...

**Comment by glattercj** [comment]
> @glattercj yeah, for the `post_start` stage I would expect that to be OK. I would expect it to mess things up in the `configure` or `pre_start` stages using the latest Docker image though...

Tried `configure` and `pre_start` with a log() statement in each. Same result...no errors on latest phenix docker image.

¯\_(ツ)_/¯

**Comment by activeshadow** [comment]
@glattercj did you look at the experiment config after running using the lastest phenix docker image (ie. `phenix config get experiment/<name>`)? I would expect the experiment spec to be empty...

I'll do a test of my own with a simple bash script to see what's going on.

**Comment by glattercj** [comment]
@activeshadow Just tested again with this branch and with latest: `configure()`, `pre_start()`, `post_start()`, and `cleanup()` all with log() statement. No errors and experiment spec was populated.

**Pull request merged**
