### PR TITLE
Move capture files to 'files' directory instead of 'captures' directory

### LINKED ISSUE #36: Fix VM packet capture commands
Both the CLI command and UI command for starting a VM packet capture require a file path, but in both cases the capture file gets renamed once the capture is stopped, so they should instead just create a temp file instead of the user having to provide a file.

Also, when a packet capture is stopped, it's moved to the `captures` directory, which won't be picked up by the UI. They should instead be moved to the `files` directory for the experiment.

### PR DESCRIPTION
**Pull request by activeshadow**
closes #36

### CODE REVIEW

**Comment by glattercj** [comment]
This is not working for me:

### CLI

1) `phenix vm capture start foobar baz 0 /phenix/tmp/TEST.pcap`
    - SUCCESS (creates `/phenix/tmp/TEST.pcap`)
2) `phenix vm capture stop foobar baz`
    - FAIL

    ```bash
    moving capture file TEST.pcap for interface 0 on VM baz in experiment foobar: rename /phenix/tmp/TEST.pcap /phenix/experiments/foobar/files/TEST.pcap: no such file or directory
    Error: Unable to stop the packet capture(s) on the baz VM
    ```

### GUI

For the UI, I do not get any option to name the file, and it doesn't appear to create any PCAP. The tap text turns green and there is a success message about starting a capture. There is also a success message about stopping the capture when clicking the green text, but after that, there is no PCAP to be found and the UI does not ask for a file path to save the capture.

**Comment by activeshadow** [comment]
@glattercj please give this another go when you have time.

**Comment by glattercj** [comment]
### CLI

1) `phenix vm capture start foobar baz 0 /phenix/tmp/TEST.pcap`
    - FAIL (creates `TEST.pcap`, but it's located in the `<exp>/files/` directory)
2) `phenix vm capture stop foobar baz`
    - SUCCESS

### GUI

Same SUCCESS for starting/stopping a capture. The capture file is saved to the `<exp>/files/` directory, but there is never an option for the user to change the path or name of the file. __*Should the user be able to change the path or the name of the capture from both the CLI and the UI?*__

**Comment by activeshadow** [comment]
@glattercj I'm now ignoring any directory path provided and instead just using the base file name provided. I'll update the docs.

**Comment by activeshadow** [comment]
@glattercj command help updated to the following:

```
> phenix vm capture start -h
Start a packet capture, using given output file as name of capture file

Usage:
  phenix vm capture start <experiment name> <vm name> <iface index> <output file> [flags]
```

**Pull request merged**
