### PR TITLE
Support referencing other scenario config when configuring apps

### LINKED ISSUE #50: Scenario config includes
**Describe your feature**
Allow a scenario config to include/reference another scenario config. 

**Expected behavior**
Most experiments will have some base scenario config. Let's say we then want to run 5 different scenarios that each add something different on top of the base scenario. Each new scenario would be it's own scenario file, but the base part of the scenario config would have to be duplicated under each of the new scenario configs. If changes are made to the base portion of the scenario config, that change currently needs to be made across all other configs. Instead, could new scenario configs reference or include a single base scenario config?

### PR DESCRIPTION
**Pull request by activeshadow**
closes #50

### CODE REVIEW

**Comment by activeshadow** [comment]
@mgaliar and/or @glattercj please test this when you have time. I've only done a smoke test confirming no compilation errors exist.

**Comment by glattercj** [comment]
@activeshadow Getting a panic on startup:

```bash
phenix      | panic: interface conversion: v2.ScenarioApp is not ifaces.ScenarioApp: missing method SetAssetDir
phenix      |
phenix      | goroutine 1 [running]:
phenix      | phenix/types.init.0()
phenix      |   phenix/types/scenario.go:22 +0xab
```

**Comment by activeshadow** [comment]
@glattercj hmmm... I'll have to look into this more. `v2.ScenarioApp` has a `SetAssetDir` implemented.

Can you share the topology and scenario configs you're using to test with?

**Comment by glattercj** [comment]
@activeshadow Not using any topo/scenario. This is from the phenix docker logs when it tries to run `phenix ui ...`

**Comment by activeshadow** [comment]
@glattercj got it... try again when you have time. Thx!

**Comment by glattercj** [comment]
@activeshadow Doesn't look like the `hosts:` info from the base-scenario is getting copied over. Using your base-scenario and actual-scenario example, I have a topo called `foobarbaz` with a node called `foobar` and a base-scenario with the `foobar` node having some metadata under the `baz-app` user app. In the app's configure() stage, one of the first things I do is call `self.extract_nodes_type("foobar")`, but it can't find any hosts (which are defined in the `base-scenario`'s `baz-app`):

```bash
$> phenix exp create foo -t foobarbaz -s actual-scenario
[✓] 'ntp' default app (configure)
[✓] 'serial' default app (configure)
[✓] 'startup' default app (configure)
[✓] 'vyatta' default app (configure)
configure
Traceback (most recent call last):
...
    nodes = self.extract_nodes_type("foobar")
...
box.exceptions.BoxKeyError: "'Box' object has no attribute 'hosts'"
[✗] 'baz-app' experiment app (configure)
```

**Comment by activeshadow** [comment]
@glattercj app hosts are now being copied over. I've tested this locally and think it's working fine.

**Pull request merged**
