### PR TITLE
Delete experiment snapshots and base directory when experiment is deleted

### LINKED ISSUE #33: Delete snapshot images when an experiment is stopped and the base directory when an experiment is deleted

### PR DESCRIPTION
**Pull request by activeshadow**
Also delete experiment snapshots before an experiment is started.

closes #33

### CODE REVIEW

**Comment by glattercj** [comment]
Not sure if this is addressing the issue or the PR. Here are my findings for both:

Issue:
1) delete snapshot images when experiment is stopped
    - FAIL
2) delete base directory when experiment is deleted
    - SUCCESS

PR:
1) delete experiment snapshots when experiment is deleted
    - FAIL
2) delete base directory when experiment is deleted
    - SUCCESS

**Comment by activeshadow** [comment]
I decided not to delete snapshots when an experiment is stopped, and instead delete them right before an experiment is started. So, the first `FAIL` above is expected. However, the other `FAIL` above is not expected.

Thanks for testing. I'll look into it.

**Comment by activeshadow** [comment]
@glattercj please give this another go when you have time.

**Comment by glattercj** [comment]
@activeshadow LGTM, but is this also supposed to delete the experiment directory where the `files/` are located? E.g. `/phenix/images/foobar/{files,miniccc_responses, ...}`? I only ask because that's also where the snapshot files get saved and those can be very large. It would make sense when you delete an experiment to also delete that directory. Maybe instead of deleting the entire directory (since it may be the same name experiment as another phenix instance on the same cluster), this just deletes those things under `files/` such as snapshots and captures?

**Comment by activeshadow** [comment]
@glattercj yeah but even then we might end up deleting a snapshot from an experiment created by another headnode on the same cluster. Perhaps we need to prepend snapshot file names with the headnode name like we do initial disk snapshots. That or we fail creating an experiment if the basedir for the experiment already exists (which would prevent different headnodes on the same cluster from creating experiments with the same name). Alternatively, if a cluster is going to have multiple headnodes, perhaps etcd should be used as the config store.

**Pull request merged**
