### PR TITLE
Multi action

### LINKED ISSUE #54: Add ron/miniccc control interface to minimega proper
Original [issue 54](https://code.google.com/p/minimega/issues/detail?id=54) created by djfritz on 2014-06-19T14:28:21.000Z:

miniccc started as a standalone server/client for the in-VM control layer. This is being rewritten as a standalone client to run on the VM, and master/relay support in minimega proper.

### LINKED ISSUE #54: Action on multiple vms
Describe your feature
Allow a user to perform an action on multiple vms

Feature Details
Stage of Experiment when feature is active: (Creation, Start, Post Start, Running, Stop, Delete)
stage: 'Running'
Where should feature be visible (current phenix tab and general location or propose a new tab, or not visible)
view: 'Experiment Info Tab'

Put checkboxes next to each VM for selection
Display a set of control buttons under VM search box to perform actions:
HDD Snapshot, Memory Dump, Screenshot, Record Screen, Stop Recording

Expected behavior
Allow user to select multiple vms then perform one of the defined actions above to all vms.

### PR DESCRIPTION
**Pull request by zach-r-long**
Fixes #54

### CODE REVIEW

**Comment by activeshadow** [comment]
@dnkcom can you take a look at / test this PR when you get some time to do so?

**Review by dnkcom — COMMENTED** [review]
@zach-r-long, pretty neat idea. Thank you for putting it together. My comments are included. I was only partially successful in testing. Perhaps in future work, we could spend more time on some specific requirements.

Besides the included comments, some additional:

- I am not sure that the button placement is the best. It might be worth tinkering with various placement options.  I am wondering how they would work to the left, above the table but below the tabs (`Table  |  Files`)? Or, maybe immediately to the left of the select box but inline with it.
- It might be nice to have an ability to uncheck all checkboxes.

**Comment by zach-r-long** [comment]
@dnkcom 
Try this out, went back and reworked alot of things ....

**Comment by zach-r-long** [comment]
@dnkcom 
Installed firefox to recreate what you reported. I see no errors on the console.  I will try to get some of my guys to run this branch and look for weirdness. New commit fixes some weird things with backing images, acts more like redeploy now where it does them in series as opposed to parallel. Did notice some weirdness of the committing message from server side not being sent as expected. Therefore progress bars are hit of miss ... seems to work on a single have not put my finger on why it does not for multiple ...

**Comment by zach-r-long** [comment]
Please take a look at the latest, squashed submission. See commit for more details, short story multiple actions for selected vms, added some new action placeholders, updated some icons, fixed some bugs, improved UI for better multiple action control.

**Comment by zach-r-long** [comment]
Please take a look at the latest, squashed submission. See commit for more details, short story multiple actions for selected vms, added some new action placeholders, updated some icons, fixed some bugs, improved UI for better multiple action control.

**Comment by activeshadow** [comment]
> Please take a look at the latest, squashed submission. See commit for more
> details, short story multiple actions for selected vms, added some new action
> placeholders, updated some icons, fixed some bugs, improved UI for better
> multiple action control.

Sorry for the delay in looking at this! Working on project-specific deliverables
at the moment. We will get to this as soon as possible!

Thanks again for contributing!

**Comment by activeshadow** [comment]
@zach-r-long just letting you know we haven't forgotten about this PR! We've been working hard to finish up the new State of Health feature on time, which was merged in earlier today.

We'll try to get to this soon!

**Comment by activeshadow** [comment]
@zach-r-long I'm getting ready to pull all the phenix-relevant code out of this repository and into it's own repo at `activeshadow/phenix`. I'd like to make the move prior to getting this PR reviewed and merged, so I'm hoping you can help me out.

Once I filter out all the phenix-related commits and push them to the new repo, I'll get you the commit hash that you should re-apply this patch to (I've tested this already and it works as expected). I'll provide you with the exact commands to run once it's time to do so.

Once we get this moved over I'll make reviewing and merging this PR a priority. Sound good to you?

**Comment by zach-r-long** [comment]
Roger that. Standing by.

~Zach

**Comment by activeshadow** [comment]
@zach-r-long OK, so here's the process:

1. Fork the new `activeshadow/phenix` repo and clone it locally.
2. In your local `phenix` repo, run `git checkout 596feea && git checkout -b multiAction` to get to the same commit in the new repo that this PR is currently based on.
3. Download the patch for this commit into the root of your local `phenix` repo via something like `wget https://github.com/activeshadow/minimega/pull/55.patch`.
4. Apply the patch using `git apply -3 -p2 55.patch`.
5. Commit the patch, push it up, and create a new PR.

Let me know if you have any issues!

**Pull request closed without merging**
